### ISSUE TITLE
[discussion] Replace the current build system(s) with CMake

### ISSUE THREAD

**Issue by zach2good** [project-topaz/topaz#1002]
**Points for**
- Adding files will become easier
- Only a single build system to be concerned about
- Building on Linux won't pollute the base of the repo with objects anymore
- Management of compilation flags will become easier
- Dependencies will be easier to manage/update
- The Linux build will become less gruesome
- Visual Studio now supports CMake projects natively!
- It already exists in the project, it just needs refactoring

**Points against**
- Windows users will lose the ability to find the `.sln` file and double click it, they will have to open Visual Studio and point it at the base `CMakeLists.txt`

**Comment by m241dan** [comment]
All for this. There is literally no downside.

**Comment by Kreidos** [comment]
*Kreidos approves these changes.* :+1: :smile:

**Comment by zach2good** [comment]
Completed in https://github.com/project-topaz/topaz/pull/1007
