### ISSUE TITLE
Yagudo Howl animation recently broken

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#1034]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Yagudo Howl animation was fine 2 months ago, there musta been a change afterwards that broke it, now the animation looks all weird.

**Comment by tankfest** [comment]
This was reported on gold saucer ~3-4 weeks ago.  I'll investigate.

**Comment by tankfest** [comment]
https://www.youtube.com/watch?v=U1TcrlG8zhw&feature=youtu.be
