### ISSUE TITLE
Windurst Mission 8-2 npc not coded

### ISSUE THREAD

**Issue by whateversclever1215** [project-topaz/topaz#1085]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
windurst mission 8-2 asks you to go talk to rukususu in fei-yin to get the key item "rhinostery ring" in order to continue the mission, it's not coded

**Comment by tankfest** [comment]
Strange that this wasn't caught before?  I'll look into it now.

**Comment by zach2good** [comment]
Fixed in https://github.com/project-topaz/topaz/pull/1089
