### ISSUE TITLE
San d'Oria Quest "A Sentry's Peril" is not complete.

### ISSUE THREAD

**Issue by eyes-and-brain** [project-topaz/topaz#1099]
Glenne.lua

```
function onTrade(player, npc, trade)
    if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL) == QUEST_ACCEPTED and
        trade:hasItemQty(601, 1) and count == 1) then
            player:startEvent(513)
            npc:wait()
    end

end
```

Even when I traded "Ointment Case" to Glenne, there was no response.
There is a "count == 1" condition, but the "count" variable appears to be undefined.

**Comment by Kreidos** [comment]
Welcome! Thanks for reporting this, @eyes-and-brain

**Comment by tankfest** [comment]
I always like to find what exactly happened in these cases... for this NPC a long time ago there used to be a local variable declared in the onTrade function, ``local count = trade:getItemCount();``

Mystery solved.. this just needs to be given some 2020 attention.
