### ISSUE TITLE
San d'Oria Quest "Flyers for Regine" is not complete.

### ISSUE THREAD

**Issue by eyes-and-brain** [project-topaz/topaz#1106]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/project-topaz/topaz/blob/ed6983dbc820d0f19ba12b380e1c2fec2e7000c6/scripts/zones/Port_San_dOria/npcs/Regine.lua#L29-L44

I think the priorities (L35 and L37) are reversed.

I have now completed the distribution of all the "Magicmart Flyer" correctly and the L35 requirements seem to match.
(There is no surplus of "Magicmart Flyer".)
Correctly, the L37 conditions must match and the quest cannot be completed.

**Comment by kaincenteno** [comment]
I thought this was fixed recently and tested, did a merge mess it iup?
