### ISSUE TITLE
Game R0's while attacking Yagudo in Giddeus

### ISSUE THREAD

**Issue by residentevil80** [project-topaz/topaz#1124]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Attacking any Yagudo in Giddeus causes the game client to r0. I can engage from a distance but when i should swing the game client r0's. We discussed a possible issue with howl. Nyu claims the Quadav in Palborough also cause a r0 in the same mannor but i have not tested it myself. Attacking Yagudo in Sarutabaruta do NOT cause an r0

**Comment by ghost** [comment]
Fixed by https://github.com/project-topaz/topaz/pull/1115.
