### ISSUE TITLE
Can't enter ToAU 15 Black Coffin

### ISSUE THREAD

**Issue by jarmengaud** [project-topaz/topaz#1145]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Looking at other issues, it seemed to work at some point in the past.
When I click on the Cutter to enter the fight, my char get stuck with "Connecting to server/ Please wait" message.
Have to force close the client.

**Comment by jarmengaud** [comment]
This is on Canary branch only, note..

**Comment by zach2good** [comment]
Fixed with https://github.com/project-topaz/topaz/pull/1151
