### ISSUE TITLE
ToAU 44 Nashmeira's Plea

### ISSUE THREAD

**Issue by jarmengaud** [project-topaz/topaz#1180]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Issues with ToAU 44:

- when you first click on the blank target in Nyzul, if you cancel and come back, you will no longer get the CS
  (you will skip it and need to directly click on the entry door)
- you can't call trusts
- when you have reached the 50% on Alexander, the intermediate cutscene triggers, but ends in a black screen.
  You will need to force close the client to exit this CS (you do get hit meanwhile, so will eventually die)

**Comment by zach2good** [comment]
> when you have reached the 50% on Alexander, the intermediate cutscene triggers, but ends in a black screen.
> You will need to force close the client to exit this CS (you do get hit meanwhile, so will eventually die)

Is this totally blocking you being able to complete the fight? I'll have a look before I make the next release and see if I can get it working. Strange and broken fights are OK, fights you can't get past are not :(

**Comment by jarmengaud** [comment]
I managed to win by force closing the client, wait 2 min, and connect back! :-)
This is not an ideal workaround though^^
