### ISSUE TITLE
SMN Physical BP do 0 damage

### ISSUE THREAD

**Issue by jarmengaud** [project-topaz/topaz#1212]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

It was working a while back, so it's a recent regression.
On both release and canary branch, physical BPs do 0 damage.

**Comment by jarmengaud** [comment]
Getting 'uninitialized variable' issues on my test server with bonusacc line 31. So probably linked to:
https://github.com/project-topaz/topaz/commit/b3002407c841595e844d4dff14b5eb361c6b9450#diff-74018908d3bf0ba87f82d62c9508ce3a

**Comment by TeoTwawki** [comment]
niiiiiiiiiiiiiiiiiiiiiil fixed by #1213

**Comment by zach2good** [comment]
⭐ https://github.com/project-topaz/topaz/pull/1213
