### ISSUE TITLE
A Shantotto Ascension "That Which Curdles Blood" A strange NPC (an elongated, costume Moogle) is inserted into the cutscene.

### ISSUE THREAD

**Issue by eyes-and-brain** [project-topaz/topaz#1274]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

It occurs when you move from "Port Windurst" to "West Sarutabaruta".
It does not occur when moving from "Windurst Woods" to "East Sarutabaruta".
The cutscene IDs for the problem are "62" and "63" in "West Sarutabaruta".

- npc_list.sql
INSERT INTO `npc_list` VALUES (17248862,'csnpc','     ',0,0.000,0.000,0.000,0,50,50,0,0,112,6,2075,0x0100000375113321333133413351756182720000,32,NULL,1);

This is caused by the above records.
Deleting the above record resolves the problem.

**Comment by EpicTaru** [comment]
Is your client version the same as the server version? Oddities like this in cutscenes are usually caused by version mismatches.

**Comment by eyes-and-brain** [comment]
Thank you for your comment.

The client version is "302000904_2".
"VER_LOCK" is "2".
There is no version mismatch warning on login.

- version.conf
```
#Topaz Version Info

#Expected Client version (wrong version cannot log in)
CLIENT_VER: 30200904_2

#WE STRONGLY ADVISE AGAINST LOCKING THE SERVER TO OLDER VERSIONS. IT IS A UNIVERSALLY BAD IDEA.

#0 - disabled (every version allowed)
#1 - enabled - strict (only exact CLIENT_VER allowed, default)
#2 - enabled - greater than or equal  (matching or greater than CLIENT_VER allowed)
VER_LOCK: 2

#Current Server Version.
#TOPAZ_VER: C202008-01
```

**Comment by TeoTwawki** [comment]
#281

**Comment by ibm2431** [comment]
Capture with NPCL entry that would fix this:
https://discord.com/channels/443544205206355968/443552899675717633/733519453697998859

(Need to be in FFXI Captures Discord for link to work).
