### ISSUE TITLE
Icefall not aggro

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#1315]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Should aggro to sound and magic

**Comment by ghost** [comment]
*Sight* and magic. Castle Zvahl Baileys (S) Snoll type mob for reference.
