### ISSUE TITLE
Gobbie Box no longer working [Canary (C202010-02)]

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#1336]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Unsure if this was due to the bit stuff move to lua

[11/Oct] [20:41:24][Error] luautils::onTrigger: ./scripts/globals/gobbiemysterybox.lua:113: attempt to call method 'getMaskBit' (a nil value)

**Comment by kaincenteno** [comment]
i didn't test any of the CS that rely on writing and reading bits (like mandragoras) but i will try in a bit (get it lol puns!)

**Comment by ibm2431** [comment]
Player mask functions in [mystery box global](https://github.com/project-topaz/topaz/blob/feature/mystery/scripts/globals/gobbiemysterybox.lua#L113-L116) got [updated in release](https://github.com/project-topaz/topaz/pull/1261). `Mystery` branch isn't in release, so the uses in `mystery` are leftover stragglers.

Should be easy fix - just update references to the new functions that Wren added. Maybe check core-side mystery files too.

**Comment by jarmengaud** [comment]
This can be closed now.

**Comment by ibm2431** [comment]
#1366
