### ISSUE TITLE
Ephemeral Moogle not accepting entire trade

### ISSUE THREAD

**Issue by jarmengaud** [project-topaz/topaz#1368]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The moogle does not accept all the clusters i give him in a single trade.
For instance i trade 24 fire clusters, and he will only store 11.  Accepted number seems random

**Comment by Lunarsky9017** [comment]
IIRC the Ephemeral Moogle has problems accepting trades when it's a multiple of 4

**Comment by jarmengaud** [comment]
This was fixed a while back though (by me). Maybe my fix is wrong :)
