### ISSUE TITLE
New changes to npcutil broke canary trusts

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#1411]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Canary is broken due to keyitem flags changing from "keyItem" to "ki" from trust branch.
When trying to finish Bastok trust quest, the quest will be completed but keyitem never received.
Unsure if there is something else that might break from other branches.

**Comment by TeoTwawki** [comment]
proposed fix:
https://github.com/project-topaz/topaz/pull/1303#discussion_r502866950

**Comment by zach2good** [comment]
Changed the quests to use ki:
https://github.com/project-topaz/topaz/commit/41ee8b2e0d4ece34e29f2e92da61921af39d62e5

Also patched the function to accept keyItem if there are any leftover somewhere:
https://github.com/project-topaz/topaz/commit/f828092c6ff49a030f331626bf3ac82e915603e8
