### ISSUE TITLE
CoP 4-4 bugged, will not start

### ISSUE THREAD

**Issue by residentevil80** [project-topaz/topaz#1419]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://www.bg-wiki.com/bg/Promathia_Mission_4-4
    Check the Iron Gate in Sealion's Den for another cutscene.

Clicking the iron gate does not trigger cutscene. Gate also open which it is not ever supposed to do.
server spits out error 
[Error] luautils::onTrigger: scripts/zones/Sealions_Den/npcs/_0w0.lua:21: attempt to index field 'cop' (a nil value)

**Comment by ibm2431** [comment]
I believe ninja-fixed this last night if you wanna try another pull~!

**Comment by residentevil80** [comment]
*EDIT* 
Had to get 1st cutscene again and now the door triggers the second. Problem fixed!
Just pulled fresh canary. Clicking the gate no longer opens it, but also does not trigger cutscene

**Comment by Kreidos** [comment]
Good stuff
