### ISSUE TITLE
CMake build doesn't support paths containing spaces

### ISSUE THREAD

**Issue by zach2good** [project-topaz/topaz#1436]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Just... don't use a path that has spaces in for now...
😢

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/97174122-07cf5d00-1768-11eb-89a9-df32a5fe3276.png)
noooooooooooooooooooooooo

**Comment by Kreidos** [comment]
People using spaces in file paths?! What savagery is this? D:

**Comment by Bizzle-Dapp** [comment]
I.... I'm sorry....
