### ISSUE TITLE
Client Version 30201103_1 / 30201103_3 Crash when Status -> Profile is accessed

### ISSUE THREAD

**Issue by neuromancerxi** [project-topaz/topaz#1524]
Issue:

Accessing the Profile Menu causes the client to crash.

Affected Client Versions:

`30201103_1`
`30201103_3`

Steps to Replicate:

Be on either of the above mentioned client versions.
Log in a character.
Open The Main Menu (- key) > Select Status > Select Profile
Client will crash.

Additional Notes:

This was tested against Canary `ea135512f18bc2e0da51d154883c9c0d8dc1b37c`
Client version `30201006_1` does not exhibit this behavior when tested against the above version of Canary.

**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by ghost** [comment]
[2020-11-14_18-02.zip](https://github.com/project-topaz/topaz/files/5541582/2020-11-14_18-02.zip)
Attached retail captures for accessing status->profile.

**Comment by zach2good** [comment]
Fixed by: https://github.com/project-topaz/topaz/commit/be34888ce2c2727bf233d8acbaf8c3e2d284a194
