### ISSUE TITLE
November Client - Tell message packet has changed

### ISSUE THREAD

**Issue by ghost** [project-topaz/topaz#1534]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

■ Occurrence Rate: 5 out of 5
■ Precondition:
1. Two characters are logged in to the server

■ Procedure:
1. Send tell from first character to second
2. Send tell from second character to first

■ Observations:
- Expected Result
1. Tell should be received successfully by the intended recipient

- Actual Result
1. Tell is not received by the intended recipient

■ Fault Recovery:
None

**Comment by ghost** [comment]
Creating this issue for tracking purposes.  Need to collect retail data for incoming chat to verify changes in addition to outgoing.

**Comment by TeoTwawki** [comment]
the previous update removed a null byte that was sent with the name in chat packets. now, I believe the name has been shifted over and a new byte added preceding it for the purposes of displaying an icon. This may be the cause of the issue. That byte would likely not be used by all forms of chat (I think its only the new assiste/assistj channels) but the packet probably still expects the name moved over and a placeholder byte at a minimum. Worth trying and seeing what happens.

**Comment by ghost** [comment]
Shifting the start bytes for name and message resolved the immediate issue.  Working now to confirm the function of this additional byte, document, and ensure that non-null values will not disrupt function.

**Comment by ghost** [comment]
Closing issue after #1538 merge.
