### ISSUE TITLE
Submodule 'navmeshes' (https://github.com/project-topaz/xiNavmeshes.git) are private

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#334]
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
```git clone --recursive``` fails as navmeshes submodule is set to private

**Comment by project-topaz** [comment]
I had failed to push the repository to GitHub.

https://github.com/project-topaz/topaz/commit/a5c0d7abf2d7f14ad007f27251e68b9b9c48e452

Confirmed with kaincenteno that recursive cloning is now working.
