### ISSUE TITLE
Crafting Skill up not working when set to 1.0

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#401]
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Get crafting to level 25.
Get a level 30 kit.

After 8 stacks of level 30 kit. No skill ups will happen. Formula seems to be bad when setting chance of crafting skill up to 1.0

**Comment by TeoTwawki** [comment]
Just for clarification: you were able to reach 25 at that same setting right? I mean this is not turn it to 1.0 and skillups break, this is with it at 1.0 thats as far as you could go and ***then*** skillups just stopped right?

**Comment by kaincenteno** [comment]
@TeoTwawki  to clarify:
Server was on 2x settings, then reverted to 1.0 for retail accuracy.

I was already level 25 crafting when starting to test 1.0

I did try skilling a craft from 0 to 1 and it increased normally. Did not test when it stops skilling up

**Comment by TeoTwawki** [comment]
K so going from 0 to 1 is possible at 1.0 rate then? That would support the theory I was floating in discord about bad scaling.

**Comment by kaincenteno** [comment]
@kaincenteno  yes, going from 0 to 1 at 1.0 rate is possible.

**Comment by kaincenteno** [comment]
crafting at level 40 stops when the rate is set to 2.6

**Comment by TeoTwawki** [comment]
I've made it above 40 with it at 2.6 it just turns agonizingly slow. made it to 100 with it at 3.0

**Comment by kaincenteno** [comment]
disregard my last message, it was a dumb moment i forgot i was capped lol. thanks @TeoTwawki

**Comment by ibm2431** [comment]
#779
