### ISSUE TITLE
Error importing database

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#407]
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When importing database through terminal using mysql get the following errors:
Importing account_ip_record.sql into the database...mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1067 (42000) at line 12: Invalid default value for 'login_time'

**Comment by TeoTwawki** [comment]
has to do with mysql version no longer supporting that format as a default.

**Comment by TeoTwawki** [comment]
https://stackoverflow.com/questions/25349126/how-can-i-set-the-default-value-of-a-field-as-0000-00-00-000000#25351733

**Comment by kaincenteno** [comment]
Changed wiki to use mariadb and libmariadb instead of mysql (just like windows build) , this resolves issue.
