### ISSUE TITLE
Mounted status staying on when attacking a mob

### ISSUE THREAD

**Issue by zach2good** [project-topaz/topaz#412]
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

While mounted you can use the attack action to hop off of your mount and start attacking a mob. When you do so the "Mounted" status remains until you strike the enemy.

When you hit the dismount button you correctly lose the mounted status.

I have tested that you cannot call your mount in combat.

Tested on a few different mounts.

This is probably a good first issue for someone wanting to poke around in core.

This on player engage might be one direction to investigate 👍 

```
        if (PChar->StatusEffectContainer->HasStatusEffect(EFFECT_MOUNTED))
        {
            PChar->StatusEffectContainer->DelStatusEffect(EFFECT_MOUNTED);
        }
```

Or maybe:
```
targ:delStatusEffect(tpz.effect.MOUNTED)
```
in the mounted effect, who knows?

![image](https://user-images.githubusercontent.com/1389729/76542400-97502600-648d-11ea-8413-0c212bc1ee03.png)

**Comment by ibm2431** [comment]
> While mounted you can use the attack action to hop off of your mount and start attacking a mob.

Is this retail? I'll admit to never having tried it. Does the action appear in the menu?

(Reading this due to #417 , making sure that we shouldn't be blocking the attack action outright.)

**Comment by TeoTwawki** [comment]
@ibm2431  on retail your character will do a dismount animation but the initial melee attack will happen before the animation is completed (dmg is in log already) so it doesn't block it at all
