### ISSUE TITLE
Padfoot drops incorrect

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#420]
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The real padfoot does not drop anything due to a mistake in his scripting:
release/scripts/zones/Lufaise_Meadows/mobs/Padfoot.lua

```lua
function onMobSpawn(mob)
    if mob:getID() == ID.mob.PADFOOT[GetServerVariable("realPadfoot")] then
        mob:setDropID(4478)
    else
        mob:setDropID(2734)
    end
end
```

setDropID(4478); number should be 2911, correlating to padfoot's actual drops from the release mob_droplist table.

**Comment by TeoTwawki** [comment]
[Both drop IDs were wrong.](https://github.com/project-topaz/topaz/pull/421)

**Comment by TeoTwawki** [comment]
#421
