### ISSUE TITLE
Windurst 6-2 shows the wrong name in the BCNM selection screen

### ISSUE THREAD

**Issue by mrhappyasthma** [project-topaz/topaz#436]
When selecting the BCNM to enter in Balga's Den, it lists it as "Divine Punishers". Which is a different event. But if you select it, it properly puts you into the Saintly Invitation BCNM and everything works as expected.

**Comment by wrenffxi** [comment]
I could not reproduce this on release branch with latest client version 30200304_3.

* When I click Burning Circle with 6-2 flagged, I get menu: None / Saintly Invitation

* When I trade Moon Orb to Burning Circle, I get menu: None / Divine Punishers / Wild Wild Whiskers

This is correct behavior.

@mrhappyasthma Any additional info you can share to help us attempt to replicate?

**Comment by mrhappyasthma** [comment]
My client version appears to be the same: `30200304_3`.

I'm playing on a custom server I don't have access to, so it's possible they have an older build that introduces the bug.

We can close this out if it's not reproducible.

**Comment by mrhappyasthma** [comment]
Marking as not reproducible.
