### ISSUE TITLE
Tutorial Exp rewards too high

### ISSUE THREAD

**Issue by Noikar** [project-topaz/topaz#455]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

tutorial should give 800 exp and then 1000 for completion, rather than 1200 and 2500

**Comment by Noikar** [comment]
scripts\quests\tutorial.lua lines 103 and 110

**Comment by ibm2431** [comment]
Fixed by #516
