### ISSUE TITLE
Closed Position trait is given freely at 75 without putting merits in it.

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#512]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```INSERT INTO `traits` VALUES (96,'closed position',19,75,1,0,0,'WOTG',0);```

It is supposed to be obtained from merit group 2, but any 75 dnc gets it.

**Comment by ibm2431** [comment]
Fixed by #526
