### ISSUE TITLE
BRD Mazurka should be allowed in dungeons (and removal on hit or attack)

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#528]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Bard Mazurka currently is not removed when taking an action against an enemy or when getting hit (https://ffxiclopedia.fandom.com/wiki/Mazurka)

Also it should work in dungeons (https://www.bg-wiki.com/bg/Category:Mazurka) Currently if tried to cast on a dungeon shows "you cannot use raptor mazurka in this area)

**Comment by kaincenteno** [comment]
the casting should be an easy fix, took a look at the zone.cpp and it looks like its received from the zone db under misc. (just need to be patient whomever gets to work on it)

**Comment by TeoTwawki** [comment]
I dunno if SE kept it (as it was always stupid tbh) but that used to be a legit retail restriction on it. I never understood why.

Edit: it was updated out, took forever to find the patch it happened in.

**Comment by ghost** [comment]
Fixed by https://github.com/project-topaz/topaz/pull/539.
