### ISSUE TITLE
Two different settings for server JP midnight time.

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#552]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

**scripts\global\settings.lua:**
TIMEZONE_OFFSET = 9.0 -- Offset from UTC used to determine when JP Midnight is for the server.  Default is JST (+9.0).

**conf\map.conf:**
#Determine when JP midnight is.
vanadiel_time_offset: 8

Redundant settings, only one can/should be used.

Also if possible, maybe an option should be to pick it directly from the OS time.

**Comment by cocosolos** [comment]
I think `vanadiel_time_offset` is used to control the in-game time/year, while `TIMEZONE_OFFSET` is used for gating requirements.

Edit: `vanadiel_time_offset` doesn't actually look like it does anything right now, but that seems to have been the intention at one time.

**Comment by tankfest** [comment]
The comments both state they are for determining when "JP midnight" is.  If vanadiel_time_offset isn't used for anything, perhaps it should be removed.

**Comment by cocosolos** [comment]
I actually think the ~~setting should maybe be renamed~~ comment should be clarified and the feature implemented. It sounds like it would let you reboot your server and have it be days or years ahead in Vana'diel, and that could be useful.
