### ISSUE TITLE
treasure caskets not popping after mob death

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#566]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
on canary branch, when killing a mob and casket_drop_rate is 0.1 or 1, no treasure chest show up afterwards. Tried it on sarutabaruta and runfare.

**Comment by Omnione** [comment]
This was cuased by a local var not being checked correctly

issue is fixed in PR #568

**Comment by kaincenteno** [comment]
@Omnione now they pop, but cannot be interacted with (wasn't sure if i had to open a new bug)

**Comment by ibm2431** [comment]
Remaining unopenable issue fixed in #573
