### ISSUE TITLE
trust not using magic or job ability

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#569]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
just tested the canary branch to see the changes made by PR #454 . Kupipi doesn't cast magic and naji still doesnt provoke. (Curilla no casting either, didn't try shantoto)

**Comment by kaincenteno** [comment]
this is experienced when the server is built on ubuntu 18.04

**Comment by brianmask** [comment]
Seeing this as well on a fresh canary build. 
git rev-parse --short HEAD == 741211aade
Linux - Debian bullseye/sid 

Nothing odd seen in the logs. Will attempt to debug for more info.

**Comment by kaincenteno** [comment]
I just checked and windows works well. thank for your feedback @brianmask

**Comment by brianmask** [comment]
trustentity.h
`// Note: The default name is the lowercase spell script name, so we override GetName()
    // to return the packetName instead, which makes the behaviour consistant with other uses
    // of GetName()
    const int8* GetName() override;
`
trustentity.cpp
`const int8* CTrustEntity::GetName()
{
    return (const int8*)packetName.c_str();
}`

is the cause of this issue
with the current implementation GetName is returning the packet_name column from the database which is used for client formatting.  Normally GetName returns the name column which is what scripts are named by.

Windows don't care about file name casing, so it finds trust.lua when Trust.lua is given.  Linux does, it wants to find exactly what you told it to find so Trust.lua will not resolve to the file.... trust.lua.

I'm not sure if there is a reason for this override of the baseentity implementation, but this override is causing the issue in Linux.

**Comment by brianmask** [comment]
https://github.com/project-topaz/topaz/pull/576

**Comment by kaincenteno** [comment]
Resolved on #576
