### ISSUE TITLE
crystal teleport not showing correct price

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#602]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

when you have tpz.ki.RHAPSODY_IN_WHITE, the crystal teleport will charge 80% less than usual without issues, the only issue is that it will still tell you the original price on the menu screen and not the discounted price.

**Comment by wrenffxi** [comment]
Closed via #915
