### ISSUE TITLE
Full Speed Ahead! not starting correctly.

### ISSUE THREAD

**Issue by Xlaits** [project-topaz/topaz#603]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

After obtaining the Chocobo License, and the Map of the Jeuno Area, talking to Mapitoto plays the correct cutscene, and does dump the PC in Batallia Downs, but the PC is NOT mounted on the Raptor. The Markers for the quest are still in the map, however.

EDIT:
Returning to Mapitoto causes the cutscene to replay, and the PC to be dumped back out into Batallia Downs.

**Comment by ibm2431** [comment]
#607 
#774
