### ISSUE TITLE
begone magic number

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#656]
https://github.com/project-topaz/topaz/blob/687167f7276edd473ca31e84d66f8e86b06290b3/scripts/zones/RuLude_Gardens/npcs/_6r9.lua#L22

255 should be replaced with `tpz.mission.id.[nationHere].NONE` or as currently this quest is broken without it

pleas tag it with easy fix along with check for that magic number

**Comment by cocosolos** [comment]
Fixed in #634

**Comment by kaincenteno** [comment]
thank you @cocosolos
