### ISSUE TITLE
Sandy Mission 6-2 No longer requires Wait, Zone only. 

### ISSUE THREAD

**Issue by mrmclaw** [project-topaz/topaz#724]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

For Sandy Mission "Ranperre's Final Rest", Which is mission 6-2 it is currently coded it looks like to wait 1 day. It use to be wait 1 Japanese midnight, but the most current guides state it just requires a zone. 

Can we change the OS wait to a need zone true? 

Thank you!
Goliath from Canaria

**Comment by tankfest** [comment]
Fixed by #731.
Hello Goliath ^.^

**Comment by ibm2431** [comment]
#731
