### ISSUE TITLE
Limit Breaker Key Item

### ISSUE THREAD

**Issue by genesius149** [project-topaz/topaz#741]
- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

Nomad Moogle in Ru'Lude Gardens won't give Limit Breaker Key Item after reaching level75, he only offers next Genkai even though I want to stay caped 75 for now. I'm on Canaria Server.

**Comment by kaincenteno** [comment]
@genesius149 =( nobody reads my messages lol, it is not working cuz im working on the last genkai, you can close this issue.

**Comment by ibm2431** [comment]
I'm assuming kaincenteno means that Canaria currently has a modified script for the Moogle. [Our current scripting for the Moogle has it bestowing the Limit Breaker as the first check.](https://github.com/project-topaz/topaz/blob/release/scripts/zones/RuLude_Gardens/npcs/Nomad_Moogle.lua#L35-L36)
