### ISSUE TITLE
Geyser doesn't work in  Dangruf wadi 

### ISSUE THREAD

**Issue by jpleake2003** [project-topaz/topaz#782]
When trying to complete the Bastok Mission Geological Survey cannot proceed to the upper cliff using Geyser..

**Comment by Kreidos** [comment]
Hi Jpleake,

Per most wikis, I don't think that geyser is used to progress up the cliff. Standing on it when it goes off merely triggers your blue acidity tester.

**Comment by ghost** [comment]
Hello and welcome!

I'm unable to reproduce this. Just tried seconds ago on the latest canary (release should be the same)/client version using the same geyser described in the 1-2 Bastok mission, A Geological Survey, here: https://www.bg-wiki.com/bg/Bastok_Mission_1-2 south east of (I-8):

![1](https://user-images.githubusercontent.com/40763842/85963874-e6c44e80-b9b7-11ea-92e9-768efd050f74.jpg)

**Comment by jpleake2003** [comment]
Thank you I repulled

**Comment by zircon-tpl** [comment]
Hello, jpleake2003!

Did pulling the repository a second time resolve this issue?

**Comment by ibm2431** [comment]
Going to assume this has been resolved. If not, let us know!
