### ISSUE TITLE
Physical damage 1H Weaponskill not working (also h2h)

### ISSUE THREAD

**Issue by dleeshus** [project-topaz/topaz#783]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
- latest canary build

I was playing around with dagger skillchains and noticed that dancing edge was not doing any damage while cyclone was.
 Shark Bite was also not working.  I say not working because the logs say the weapon skill is readied and then there is no message for miss or 0 damage, it is just blank as if it never happened 

Also tested combo and shoulder tackle which both don't work for H2H.

Shining Strike dealt some damage while Brainshaker does not work for club.

We reverted commit 743dc2f53c5cb146336e69f55e375d5524dcd594 " Add var and binding for isDualWielding + remove presumptuous granting" and the damage is working again.

**Comment by ibm2431** [comment]
Did you recompile core?

**Comment by dleeshus** [comment]
I will check with the server admin but if I had to guess, probably not.

I'll have him recompile and confirm.

Thanks for the prompt reply.

**Comment by dleeshus** [comment]
not recompiling the core was the issue.

sorry and thanks!

**Comment by ibm2431** [comment]
👍
