### ISSUE TITLE
Tiny Turtles in Qulun

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#838]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Ruby, adaman, and ancient (I think) quadavs in Qulun dome suffer from tinyism.  This is an issue with their flag settings, not model id, as discussed on Discord.
![image](https://user-images.githubusercontent.com/37684138/87233352-5b659880-c37b-11ea-9543-e9ab45300ec7.png)

**Comment by TeoTwawki** [comment]
~~Island Dwarfism~~ _Dome Tinyism_
