### ISSUE TITLE
Coullene  looks over curiously for a moment

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#865]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This happens when Flyer for Regine hasn't been accepted.

**Comment by kaincenteno** [comment]
Looking curiously no more

**Comment by kaincenteno** [comment]
actually reopening it so a Tester can check the quest

**Comment by wrenffxi** [comment]
Closed via #861, retested
