### ISSUE TITLE
Daily reset time does not honor "JP Midnight" default setting

### ISSUE THREAD

**Issue by jarmengaud** [project-topaz/topaz#875]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Things that are supposed to reset daily or weekly (tally, guild items,...), are not resetting at JP midnight with default configuration, even though by default:
TIMEZONE_OFFSET = 9.0 -- Offset from UTC used to determine when "JP Midnight" is for the server.  Default is JST (+9.0). 

If you look at the time_server.cpp code, you will see things like:
    //Midnight
    if (CVanaTime::getInstance()->getSysHour() == 0 && CVanaTime::getInstance()->getSysMinute() == 0)

so it is hardcoded that reset will happen at midnight for the server local time zone. And cannot be changed by a configuration either.

Would probably fix:
https://github.com/project-topaz/topaz/issues/22

**Comment by jarmengaud** [comment]
Well of course, you could change the server time zone for JST, but I am not sure admins would like this...

**Comment by Altalus** [comment]
Darkstar had the `vanadiel_time_offset` setting in the `conf/map.conf` but it seems topaz does not :)
