### ISSUE TITLE
Most trusts unable to be casted on Canary branch

### ISSUE THREAD

**Issue by kaincenteno** [project-topaz/topaz#882]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Just updated canaria server with commit up to b4f27a70daeb33751a40f760678f5f38624cf63f, and most of the trusts are unable to be cases, for example Naji, Nanah, Ayame, Excenmille, Curilla, Voker.

I can summon Kupipi, Shantoto, Ajido Marujido, and Lion II

**Comment by zach2good** [comment]
Should be fixed with:
https://github.com/project-topaz/topaz/pull/884

**Comment by kaincenteno** [comment]
Thank you for recognizing the solution =)
