### ISSUE TITLE
Feature Request: En-stun modifier for mobs

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#947]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

King Behemoth has a natural en-stun modifier on attacks, but we have no clean way to add it currently.

This is partially requested as well in #51 and #117

**Comment by TeoTwawki** [comment]
Yes we do. I’ll add it when I get home

**Comment by TeoTwawki** [comment]
#951
