### ISSUE TITLE
Feature Request:  Command to add/remove mods from an entity manually

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#967]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

We can use !getmod to see what the value of a mod is on an entity.  For testing new/changed mods functionality it'd be nice to have the ability to change mod values for ourselves and others at a whim.

**Comment by wrenffxi** [comment]
Closed via #972, which is now in release
