### ISSUE TITLE
Bartholomew's Knife mini-quest doesn't work

### ISSUE THREAD

**Issue by tankfest** [project-topaz/topaz#978]
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Can't obtain [Bartholomew's Knife](https://ffxiclopedia.fandom.com/wiki/Bartholomew's_Knife).

Thanks to Nireya@GoldSaucer for reporting this.

**Comment by zach2good** [comment]
This should now work as of:
https://github.com/project-topaz/topaz/pull/980

Functions: "pretty much", there are still unresolved questions that are logged here:
https://github.com/project-topaz/topaz/issues/1162
